/*! @file libbrsar.c
 *  @brief offsetFromString for making stuff easier.
 *  @since 2014-02-14
 *
 *  This file contains the offsetFromString function, which converts the given
 *  filename to its respective offset in the BRSAR.
 */
#include "libbrsar.h"
#include <string.h>

/*int offsetFromString(char* str) {
	if (strcmp("N_BLOCK_F", str)==0)
		return N_BLOCK_F;
	if (strcmp("N_BLOCK_N", str)==0)
		return N_BLOCK_N;
	if (strcmp("N_BOSSMI_32", str)==0)
		return N_BOSSMI_32;
	if (strcmp("N_CASINO_F", str)==0)
		return N_CASINO_F;
	if (strcmp("N_CASINO_N", str)==0)
		return N_CASINO_N;
	if (strcmp("N_CIRCUIT32_F", str)==0)
		return N_CIRCUIT32_F;
	if (strcmp("N_CIRCUIT32_N", str)==0)
		return N_CIRCUIT32_N;

	return -1;
}*/

// Generated by script!
int offsetFromString(char* str) {
	if (strcmp("N_BLOCK_F", str)==0)
		return N_BLOCK_F;
	if (strcmp("N_BLOCK_N", str)==0)
		return N_BLOCK_N;
	if (strcmp("N_BOSSMI_32", str)==0)
		return N_BOSSMI_32;
	if (strcmp("N_CASINO_F", str)==0)
		return N_CASINO_F;
	if (strcmp("N_CASINO_N", str)==0)
		return N_CASINO_N;
	if (strcmp("N_CIRCUIT32_F", str)==0)
		return N_CIRCUIT32_F;
	if (strcmp("N_CIRCUIT32_N", str)==0)
		return N_CIRCUIT32_N;
	if (strcmp("N_DAISY32_F", str)==0)
		return N_DAISY32_F;
	if (strcmp("N_DAISY32_N", str)==0)
		return N_DAISY32_N;
	if (strcmp("N_FARM_F", str)==0)
		return N_FARM_F;
	if (strcmp("N_FARM_N", str)==0)
		return N_FARM_N;
	if (strcmp("N_KINOKO_F", str)==0)
		return N_KINOKO_F;
	if (strcmp("N_KINOKO_N", str)==0)
		return N_KINOKO_N;
	if (strcmp("N_MAPLE_F", str)==0)
		return N_MAPLE_F;
	if (strcmp("N_MAPLE_N", str)==0)
		return N_MAPLE_N;
	if (strcmp("N_RAINBOW32_F", str)==0)
		return N_RAINBOW32_F;
	if (strcmp("N_RAINBOW32_N", str)==0)
		return N_RAINBOW32_N;
	if (strcmp("N_RYUUSA_F", str)==0)
		return N_RYUUSA_F;
	if (strcmp("N_RYUUSA_N", str)==0)
		return N_RYUUSA_N;
	if (strcmp("N_SHOPPING32_F", str)==0)
		return N_SHOPPING32_F;
	if (strcmp("N_SHOPPING32_N", str)==0)
		return N_SHOPPING32_N;
	if (strcmp("N_SKATE_F", str)==0)
		return N_SKATE_F;
	if (strcmp("N_SKATE_N", str)==0)
		return N_SKATE_N;
	if (strcmp("N_SNOWBOARD32_F", str)==0)
		return N_SNOWBOARD32_F;
	if (strcmp("N_SNOWBOARD32_N", str)==0)
		return N_SNOWBOARD32_N;
	if (strcmp("N_VENICE_F", str)==0)
		return N_VENICE_F;
	if (strcmp("N_VENICE_N", str)==0)
		return N_VENICE_N;
	if (strcmp("N_VOLCANO32_F", str)==0)
		return N_VOLCANO32_F;
	if (strcmp("N_VOLCANO32_N", str)==0)
		return N_VOLCANO32_N;
	if (strcmp("O_CRS_IN_FAN", str)==0)
		return O_CRS_IN_FAN;
	if (strcmp("O_CRS_IN_FAN_BATTLE", str)==0)
		return O_CRS_IN_FAN_BATTLE;
	if (strcmp("O_CRS_IN_FAN_MISSION", str)==0)
		return O_CRS_IN_FAN_MISSION;
	if (strcmp("O_CRS_IN_FAN_WIFI", str)==0)
		return O_CRS_IN_FAN_WIFI;
	if (strcmp("O_ENDING_PARTA_32", str)==0)
		return O_ENDING_PARTA_32;
	if (strcmp("O_FANFAREBTDRAW_32", str)==0)
		return O_FANFAREBTDRAW_32;
	if (strcmp("O_FANFAREGP1_32", str)==0)
		return O_FANFAREGP1_32;
	if (strcmp("O_FANFAREGP1_ONLY32", str)==0)
		return O_FANFAREGP1_ONLY32;
	if (strcmp("O_FANFAREGP2_32", str)==0)
		return O_FANFAREGP2_32;
	if (strcmp("O_FANFAREGP2_ONLY32", str)==0)
		return O_FANFAREGP2_ONLY32;
	if (strcmp("O_FANFAREGPDAME_32", str)==0)
		return O_FANFAREGPDAME_32;
	if (strcmp("O_FANFAREGPDAME_ONLY32", str)==0)
		return O_FANFAREGPDAME_ONLY32;
	if (strcmp("O_FANFAREMILOSE_32", str)==0)
		return O_FANFAREMILOSE_32;
	if (strcmp("O_FANFAREMILOSE_ONLY32", str)==0)
		return O_FANFAREMILOSE_ONLY32;
	if (strcmp("O_FANFAREMIWIN_32", str)==0)
		return O_FANFAREMIWIN_32;
	if (strcmp("O_FANFAREMIWIN_ONLY32", str)==0)
		return O_FANFAREMIWIN_ONLY32;
	if (strcmp("O_FANFAREMIWINBOSS_32", str)==0)
		return O_FANFAREMIWINBOSS_32;
	if (strcmp("O_FANFARETA1ST_32", str)==0)
		return O_FANFARETA1ST_32;
	if (strcmp("O_FANFARETA1ST_ONLY32", str)==0)
		return O_FANFARETA1ST_ONLY32;
	if (strcmp("O_HYOUSYOU_CUT", str)==0)
		return O_HYOUSYOU_CUT;
	if (strcmp("O_HYOUSYOU_LOSE", str)==0)
		return O_HYOUSYOU_LOSE;
	if (strcmp("O_HYOUSYOU_NORMAL", str)==0)
		return O_HYOUSYOU_NORMAL;
	if (strcmp("O_HYOUSYOU_WINNINGRUN", str)==0)
		return O_HYOUSYOU_WINNINGRUN;
	if (strcmp("O_OPTION_32", str)==0)
		return O_OPTION_32;
	if (strcmp("O_START2_32_FAN", str)==0)
		return O_START2_32_FAN;
	if (strcmp("O_START32_FAN", str)==0)
		return O_START32_FAN;
	if (strcmp("O_WI_FI_WAITING32", str)==0)
		return O_WI_FI_WAITING32;
	if (strcmp("R_64_BATTLE_F", str)==0)
		return R_64_BATTLE_F;
	if (strcmp("R_64_BATTLE_N", str)==0)
		return R_64_BATTLE_N;
	if (strcmp("R_64_CIRCUIT32_F", str)==0)
		return R_64_CIRCUIT32_F;
	if (strcmp("R_64_CIRCUIT32_N", str)==0)
		return R_64_CIRCUIT32_N;
	if (strcmp("R_64_JUNGLE32_F", str)==0)
		return R_64_JUNGLE32_F;
	if (strcmp("R_64_JUNGLE32_N", str)==0)
		return R_64_JUNGLE32_N;
	if (strcmp("R_64_KUPPA32_F", str)==0)
		return R_64_KUPPA32_F;
	if (strcmp("R_64_KUPPA32_N", str)==0)
		return R_64_KUPPA32_N;
	if (strcmp("R_64_SHERBET32_F", str)==0)
		return R_64_SHERBET32_F;
	if (strcmp("R_64_SHERBET32_N", str)==0)
		return R_64_SHERBET32_N;
	if (strcmp("R_AGB_BATTLE_F", str)==0)
		return R_AGB_BATTLE_F;
	if (strcmp("R_AGB_BATTLE_N", str)==0)
		return R_AGB_BATTLE_N;
	if (strcmp("R_AGB_BEACH32_F", str)==0)
		return R_AGB_BEACH32_F;
	if (strcmp("R_AGB_BEACH32_N", str)==0)
		return R_AGB_BEACH32_N;
	if (strcmp("R_AGB_KUPPA32_F", str)==0)
		return R_AGB_KUPPA32_F;
	if (strcmp("R_AGB_KUPPA32_N", str)==0)
		return R_AGB_KUPPA32_N;
	if (strcmp("R_DS_BATTLE_F", str)==0)
		return R_DS_BATTLE_F;
	if (strcmp("R_DS_BATTLE_N", str)==0)
		return R_DS_BATTLE_N;
	if (strcmp("R_DS_DESERT32_F", str)==0)
		return R_DS_DESERT32_F;
	if (strcmp("R_DS_DESERT32_N", str)==0)
		return R_DS_DESERT32_N;
	if (strcmp("R_DS_GARDEN32_F", str)==0)
		return R_DS_GARDEN32_F;
	if (strcmp("R_DS_GARDEN32_N", str)==0)
		return R_DS_GARDEN32_N;
	if (strcmp("R_DS_JUNGLE32_F", str)==0)
		return R_DS_JUNGLE32_F;
	if (strcmp("R_DS_JUNGLE32_N", str)==0)
		return R_DS_JUNGLE32_N;
	if (strcmp("R_DS_TOWN32_F", str)==0)
		return R_DS_TOWN32_F;
	if (strcmp("R_DS_TOWN32_N", str)==0)
		return R_DS_TOWN32_N;
	if (strcmp("R_GC_BATTLE32_F", str)==0)
		return R_GC_BATTLE32_F;
	if (strcmp("R_GC_BATTLE32_N", str)==0)
		return R_GC_BATTLE32_N;
	if (strcmp("R_GC_BEACH32_F", str)==0)
		return R_GC_BEACH32_F;
	if (strcmp("R_GC_BEACH32_N", str)==0)
		return R_GC_BEACH32_N;
	if (strcmp("R_GC_CIRCUIT32_F", str)==0)
		return R_GC_CIRCUIT32_F;
	if (strcmp("R_GC_CIRCUIT32_N", str)==0)
		return R_GC_CIRCUIT32_N;
	if (strcmp("R_GC_MOUNTAIN32_F", str)==0)
		return R_GC_MOUNTAIN32_F;
	if (strcmp("R_GC_MOUNTAIN32_N", str)==0)
		return R_GC_MOUNTAIN32_N;
	if (strcmp("R_GC_STADIUM32_F", str)==0)
		return R_GC_STADIUM32_F;
	if (strcmp("R_GC_STADIUM32_N", str)==0)
		return R_GC_STADIUM32_N;
	if (strcmp("R_SFC_BATTLE_F", str)==0)
		return R_SFC_BATTLE_F;
	if (strcmp("R_SFC_BATTLE_N", str)==0)
		return R_SFC_BATTLE_N;
	if (strcmp("R_SFC_CIRCUIT32_F", str)==0)
		return R_SFC_CIRCUIT32_F;
	if (strcmp("R_SFC_CIRCUIT32_N", str)==0)
		return R_SFC_CIRCUIT32_N;
	if (strcmp("R_SFC_OBAKE32_F", str)==0)
		return R_SFC_OBAKE32_F;
	if (strcmp("R_SFC_OBAKE32_N", str)==0)
		return R_SFC_OBAKE32_N;
	if (strcmp("STRM_ME", str)==0)
		return STRM_ME;
	if (strcmp("STRM_N_DESERT_F", str)==0)
		return STRM_N_DESERT_F;
	if (strcmp("STRM_N_DESERT_N", str)==0)
		return STRM_N_DESERT_N;
	if (strcmp("STRM_N_FACTORY_F", str)==0)
		return STRM_N_FACTORY_F;
	if (strcmp("STRM_N_FACTORY_N", str)==0)
		return STRM_N_FACTORY_N;
	if (strcmp("STRM_N_KOOPA_F", str)==0)
		return STRM_N_KOOPA_F;
	if (strcmp("STRM_N_KOOPA_N", str)==0)
		return STRM_N_KOOPA_N;
	if (strcmp("STRM_N_RIDGEHIGHWAY_F", str)==0)
		return STRM_N_RIDGEHIGHWAY_F;
	if (strcmp("STRM_N_RIDGEHIGHWAY_N", str)==0)
		return STRM_N_RIDGEHIGHWAY_N;
	if (strcmp("STRM_N_TRUCK_F", str)==0)
		return STRM_N_TRUCK_F;
	if (strcmp("STRM_N_TRUCK_N", str)==0)
		return STRM_N_TRUCK_N;
	if (strcmp("STRM_N_WATER_F", str)==0)
		return STRM_N_WATER_F;
	if (strcmp("STRM_N_WATER_N", str)==0)
		return STRM_N_WATER_N;
	return -1;
}
